LOG_OP(SMALL_DICK, Op_Below)

LOG_OP(NICE_SMALL_DICK, Op_Below_Eq)

LOG_OP(BIG_DICK, Op_Above)

LOG_OP(NICE_BIG_DICK, Op_Above_Eq)

LOG_OP(NICE_DICK, Op_Eql)

LOG_OP(ASS, Op_And)

LOG_OP(ORAL_SEX, Op_Or)

LOG_OP(PUSSY, Op_Not_Eql)