all: disasmtask

FLAGS = -D _DEBUG -ggdb3 -std=c++17 -O0 -Wall -Wextra -Weffc++\
 -Wc++14-compat -Wmissing-declarations\
  -Wcast-align -Wcast-qual -Wchar-subscripts\
   -Wconversion -Wctor-dtor-privacy -Wempty-body -Wfloat-equal\
    -Wformat-nonliteral -Wformat-security -Wformat=2\
	 -Winline -Wlong-long -Wnon-virtual-dtor -Wopenmp\
	 -Wpacked -Wpointer-arith -Winit-self -Wredundant-decls -Wshadow\
	   -Wsign-conversion -Wsign-promo -Wstrict-overflow=2\
		 -Wsuggest-override -Wswitch-default -Wswitch-enum -Wundef\
		  -Wunreachable-code -Wunused -Wvariadic-macros\
		   -Wno-literal-range -Wno-missing-field-initializers -Wno-narrowing\
		    -Wno-old-style-cast -Wno-varargs -Wstack-protector -fcheck-new\
			 -fsized-deallocation -fstack-protector -fstrict-overflow -fno-omit-frame-pointer\
			  -Wlarger-than=8192 -fPIE\
			   -fsanitize=address,alignment,bool,bounds,enum,float-cast-overflow,\
			   -fsanitize=float-divide-by-zero,integer-divide-by-zero,nonnull-attribute,null,\
			   -fsanitize=address,signed-integer-overflow,undefined,unreachable,vla-bound,vptr,

disasmtask: main.o disasm.o
	g++ disasm_obj/main.o disasm_obj/disasm.o $(FLAGS) -o disasmbly

main.o: ./disasm_src/main.cpp
	g++ -c ./disasm_src/main.cpp $(FLAGS) -o disasm_obj/main.o

disasm.o: ./disasm_src/disasm.cpp
	g++ -c ./disasm_src/disasm.cpp $(FLAGS) -o disasm_obj/disasm.o

preproc: ./disasm_src/disasm.cpp
	g++ -c disasm_src/disasm.cpp $(FLAGS) -E -o disasm_obj/preproc.cpp

.PHONY: clean